// Auto-generated by dex-creator. Do not edit.

import * as tarnadasOrderbookShimmerPluginModule from "@tarnadas/orderbook-shimmer-plugin";
import "@tarnadas/orderbook-shimmer-plugin/dist/styles.css";
export const dexPlugins = [
  { pluginId: "tarnadas-orderbook-shimmer-plugin", module: tarnadasOrderbookShimmerPluginModule },
] as const;
